# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tara forstner
tagline:          'A Simple Website'
description:      'a research website'
url:              https://taraaubrey.github.io
baseurl:          /

author:
  name:           'Tara Forstner'
  url:            https://www.waterways.ac.nz/tara-forstner-phd

paginate:         5

# Custom vars
version:          0.0.1
