# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Webpage
tagline:          'Tara's research webpage'
description:      'A simple reasearch landing page'
url:              https://taraaubrey.github.io/
baseurl:          /

author:
  name:           'Tara Forstner'
  url:            https://www.waterways.ac.nz/tara-forstner-phd

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/taraaubrey/taraaubrey.github.io
